POST http://localhost:8080/board/member/signup
Content-Type: application/json

{
  "username":"kkk12",
  "password":"12345",
  "passwordConfirm":"12345"
}

########
POST http://localhost:8080/board/member/login
Content-Type: application/json

{
  "username":"kkk12",
  "password":"12345"
}

#######
POST http://localhost:8080/board/auth/post
Authorization: BEARER eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJreSIsIkVYUElSRURfVElNRSI6MTY2MTYyMTkwNSwiVVNFUl9OQU1FIjoia2trMTIifQ.Wg8hyG-eaZmUSFIiQ17vFp1yRCFJSGx37ZZqhK3Krl8
Content-Type: application/json

{
"title":"마카롱 만들기",
"content":"사실 만들줄 모름"
}

######
GET http://localhost:8080/board/member/logout

#####
POST http://localhost:8080/board/member/signup
Content-Type: application/json

{
  "username":"kyky",
  "password":"ky1234",
  "passwordConfirm":"ky1234"
}

########
POST http://localhost:8080/board/member/login
Content-Type: application/json

{
  "username":"kyky",
  "password":"ky1234"
}

#######
POST http://localhost:8080/board/auth/post
Authorization: BEARER eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJreSIsIkVYUElSRURfVElNRSI6MTY2MTYyMTkzNywiVVNFUl9OQU1FIjoia3lreSJ9.m9PKYDTh7sHUNeh3cE9X6Qwd0zPZRlKT3_lnqmlXJe8
Content-Type: application/json

{
  "title":"마카롱 만들기2",
  "content":"사실 만들줄 모름2"
}

######
GET http://localhost:8080/board/post

######
GET http://localhost:8080/board/post/1

######
GET http://localhost:8080/board/post/4


#######
PUT http://localhost:8080/board/auth/post/2
Authorization: BEARER eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJreSIsIkVYUElSRURfVElNRSI6MTY2MTYyMTkzNywiVVNFUl9OQU1FIjoia3lreSJ9.m9PKYDTh7sHUNeh3cE9X6Qwd0zPZRlKT3_lnqmlXJe8
Content-Type: application/json

{
  "title":"초콜렛 만들기",
  "content":"초콜렛을 산다. 중탕한다."
}

#######
PUT http://localhost:8080/board/auth/post/1
Authorization: BEARER eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJreSIsIkVYUElSRURfVElNRSI6MTY2MTYyMTkzNywiVVNFUl9OQU1FIjoia3lreSJ9.m9PKYDTh7sHUNeh3cE9X6Qwd0zPZRlKT3_lnqmlXJe8
Content-Type: application/json

{
  "title":"초콜렛 만들기",
  "content":"초콜렛을 산다. 중탕한다."
}


#####

